export const SERVICE_TYPES = [
"General Inspection — Every 12 months / 20,000 km — Time: 0.5 hours",

  "---     Fluids & Filters  ---",
  "Air Filter: Replace — 20,000–30,000 km — Time: 0.2 hours",
  "Brake Fluid: Bleed — Every 2 years — Time: 0.8 hours",
  "Cabin Air Filter: Replace — 20,000–30,000 km — Time: 0.2 hours",
  "Clutch Fluid: Replace — Every 2 years — Time: 0.5 hours",
  "Coolant: Flush — Every 5 years / 100,000 km — Time: 1.0 hours",
  "Fuel Filter: Replace — 40,000–80,000 km — Time: 0.5 hours",
  "Fuel System: Clean — Every 20,000 km — Time: 0.4 hours",
  "Oil: Change — 5,000–8,000 km — Time: 0.5 hours",
  "Power Steering Fluid: Flush — Every 80,000–100,000 km — Time: 0.7 hours",
  "Radiator Cap: Pressure Test — Annually — Time: 0.1 hours",

  "---     General Maintenance ---",
  "Battery: Replace / Test — Test annually / Replace 4–6 years — Time: 0.4 hours",
  "Battery Cables: Inspect — Corrosion / looseness — Time: 0.2 hours",
  "Battery Jump / Boost — As needed — Time: 0.1 hours",
  "Battery Terminals: Clean — Annually — Time: 0.2 hours",
  "Belt: Change — 80,000–100,000 km — Time: 0.7 hours",
  "Belts: Inspect — Annually — Time: 0.1 hours",
  "Carburetor: Service — Annually — Time: 1.0 hours",
  "Chain / Sprocket: Service — Every 800–1,000 km — Time: 0.6 hours",
  "Chain Tension: Adjust — Every 500–800 km — Time: 0.2 hours",
  "Clutch Cable: Adjust — As needed — Time: 0.3 hours",
  "Drive Belt (ATV/UTV): Replace — 3,000–5,000 km or 200 hours — Time: 1.0 hours",
  "Drive Chain: Lubricate — Every 500–800 km — Time: 0.2 hours",
  "Electrical: Work — Time: Varies",
  "Engine Bay: Clean — Optional — Time: 0.5 hours",
  "Exhaust: Repair — As needed — Time: 0.8 hours",
  "Fuse: Replace — As needed — Time: 0.1 hours",
  "Headlight / Bulb: Replace — As needed — Time: 0.2 hours",
  "Hoses: Inspect — Coolant, vacuum, fuel hoses — Time: 0.2 hours",
  "Inspection — Annually — Time: 0.5 hours",
  "MAF Sensor: Clean — Every 20,000–30,000 km — Time: 0.3 hours",
  "PCV Valve: Replace — 50,000–80,000 km — Time: 0.3 hours",
  "Spark Plugs: Replace — 30,000–50,000 km — Time: 0.5 hours",
  "Throttle Body: Clean — Every 50,000 km — Time: 0.5 hours",
  "Throttle / Idle: Adjust — As needed — Time: 0.2 hours",
  "Wiper Blades: Replace — Annually — Time: 0.1 hours",

  "---     Brake Services ---",
  "Brake Calipers: Service — Every brake job — Time: 0.6 hours",
  "Brake Hardware: Service — Every brake job — Time: 0.4 hours",
  "Brake Lines: Inspect — Annually — Time: 0.2 hours",
  "Brake Pads: Replace — 30,000–70,000 km — Time: 1.0 hours",
  "Brake Rotors / Drums: Service — Every brake job — Time: 0.8 hours",
  "Parking Brake: Adjust — Annually — Time: 0.3 hours",

  "---    Tires & Wheels ---",
  "Lug Nuts: Torque Check — After tire service — Time: 0.1 hours",
  "Tire: Replace — 40,000–80,000 km — Time: 0.8 hours",
  "Tire: Rotate — Every 8,000–10,000 km — Time: 0.4 hours",
  "Wheel Bearings: Check — Annually — Time: 0.3 hours",

  "---    Steering & Suspension ---",
  "Front End Check: Ball Joints — Annually — Time: 0.3 hours",
  "Front End Check: Tie Rods — Annually — Time: 0.3 hours",

  "---    Diagnostics & Misc ---",
  "Accessory: Install — Time: 0.5–1.0 hours",
  "Charging System: Test — Annually — Time: 0.2 hours",
  "Compression Test — As needed — Time: 0.5 hours",
  "Fluid Leak: Identify — As needed — Time: 0.4 hours",
  "Full Diagnostic Scan — As needed — Time: 0.3 hours",
  "Leak-Down Test — As needed — Time: 0.7 hours",
  "Sensor Scan & Reset — As needed — Time: 0.2 hours",
  "Starter System: Test — Annually — Time: 0.3 hours",
  "Vacuum Leak: Test — As needed — Time: 0.3 hours",
  "Other",

  "---    Marine Services ---",
  "Anodes: Replace — Annually — Time: 0.4 hours",
  "Bilge Float Switch: Test — Annually — Time: 0.2 hours",
  "Bilge Pump: Service — Annually — Time: 0.5 hours",
  "Fuel Line / Primer Bulb: Replace — Every 2 seasons — Time: 0.4 hours",
  "Fuel/Water Separator: Replace — Every season — Time: 0.3 hours",
  "Lower Unit: Service — Annually — Time: 1.0 hours",
  "Marine Battery: Service — Annually — Time: 0.3 hours",
  "Marine Electrical: Diagnosis — As needed — Time: 0.5 hours",
  "Marine Spark Plugs: Replace — Every season — Time: 0.4 hours",
  "Outboard Carb: Sync — Annually — Time: 1.0 hours",
  "Outboard: Tune-Up — Annually — Time: 1.0 hours",
  "Propeller: Inspect / Replace — Every season — Time: 0.3 hours",
  "Spark Arrestor: Clean — Annually — Time: 0.4 hours",
  "Steering Cable: Lubricate — Annually — Time: 0.3 hours",
  "Water Impeller: Replace — Every 2 seasons — Time: 1.0 hours",
  "Winterization / De-Winterization — Seasonal — Time: 1.0 hours",
  "Other Marine Service"


] as const;
